name: taiper
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^1.1.2+1
  photo_view: ^0.7.0
  image_test_utils: ^1.0.0
  url_launcher: ^5.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
