name: taiper
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^1.1.2+1
  photo_view: ^0.6.0
  chewie: ^0.9.8+1
  video_player: ^0.10.2+5





dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
